### ISSUE TITLE
default styles on a table element

### ISSUE THREAD

**Issue by M-J-Robbins** [email-markup-consortium/default-email-styles#4]
## Ionons, 1&1, etc. 
```css
.mail-detail-content table {
    font-family: -apple-system,BlinkMacSystemFont,"Helvetica Neue","Segoe UI",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
    font-size: 13px;
    font-weight: 400;
    font-feature-settings: "liga" 0;
    line-height: normal;
    border-collapse: collapse;
}
```

## Applemail
Adds default styles but i can't access the stylesheet
* `font-size`
* `font-weight`
* `text-align`
* `color`
* `line-height`
* `font-style`
